#Parameters for navFn, NB: if you want to use it set the parameter base_global_planner: "navfn/NavfnROS" in the file move_base_general_params. Reference at: http://wiki.ros.org/navfn
NavfnROS:

#Specifies whether or not to allow navfn to create plans that traverse unknown space. Decided to not allow to go to unknown space
allow_unknown: false 

#Specifies the x size of an optional window to restrict the planner to. This can be useful for restricting NavFn to work in a small window of a large costmap. 
planner_window_x: 0.0 #default value TBD resize this

# Specifies the y size of an optional window to restrict the planner to. This can be useful for restricting NavFn to work in a small window of a large costmap.   
planner_window_y: 0.0

   
#A tolerance on the goal point for the planner. NavFn will attempt to create a plan that is as close to the specified goal as possible but no further than default_tolerance away.
default_tolerance: 0.0 #default value TBD resize this

#Specifies whether or not to visualize the potential area computed by navfn via a PointCloud2.
visualize_potential: false

  
